"""Tests for ClaudeMdImporter."""
import pytest
from pathlib import Path
from unittest.mock import patch, MagicMock

from memory_system.importers.claude_md_importer import ClaudeMdImporter
from memory_system.importers.base import ImportResult, ImportPreview
from memory_system.memory_ts_client import Memory


@pytest.fixture
def importer(tmp_path):
    """Create a ClaudeMdImporter with mocked client."""
    mem_dir = tmp_path / "memories"
    mem_dir.mkdir()
    imp = ClaudeMdImporter(memory_dir=mem_dir, project_id="LFI")
    mock_client = MagicMock()
    mock_client.list.return_value = []
    mock_client.create.return_value = Memory(
        id="test-id",
        content="test",
        importance=0.85,
        tags=[],
        project_id="LFI",
    )
    imp._client = mock_client
    return imp


SAMPLE_CLAUDE_MD = """\
# Project instructions

## Core behavior

### Questioning protocol

- Always ask clarifying questions before starting work
- Default to questioning when in doubt
- Use multiple choice over open-ended questions

### Response format

**Every response must end with a summary.**

**Include key decisions and rationale.**

## Code quality

### Testing rules

- Write tests first (TDD)
- Minimum 10 tests per feature
- No skipping the red phase

## Auto-generated section

<!-- AUTO-GENERATED -->
This section is auto-generated and should be skipped.
<!-- /AUTO-GENERATED -->

## Documentation

### Changelog updates

- Update CHANGELOG.md for every feature
- Use semantic versioning
"""


class TestSectionParsing:
    """Test parsing CLAUDE.md into sections."""

    def test_extracts_headings_and_content(self, importer, tmp_path):
        """Section parsing extracts headings at h2 and h3 levels."""
        claude_md = tmp_path / "CLAUDE.md"
        claude_md.write_text(SAMPLE_CLAUDE_MD)

        sections = importer._parse_sections(SAMPLE_CLAUDE_MD)

        headings = [s["heading"] for s in sections]
        assert "Core behavior" in headings
        assert "Questioning protocol" in headings
        assert "Response format" in headings
        assert "Code quality" in headings
        assert "Testing rules" in headings

    def test_nested_headings(self, importer):
        """h3 headings within h2 sections are parsed correctly."""
        content = "## Parent\n\nParent content\n\n### Child\n\nChild content\n"

        sections = importer._parse_sections(content)

        assert len(sections) == 2
        parent = next(s for s in sections if s["heading"] == "Parent")
        child = next(s for s in sections if s["heading"] == "Child")
        assert parent["level"] == 2
        assert child["level"] == 3


class TestRuleExtraction:
    """Test extracting individual rules from section content."""

    def test_bullet_point_rules(self, importer):
        """Bullet points are extracted as individual rules."""
        content = "- Always ask clarifying questions before starting work\n- Short\n- Default to questioning when in doubt\n"

        rules = importer._extract_rules(content)

        assert "Always ask clarifying questions before starting work" in rules
        assert "Default to questioning when in doubt" in rules
        # "Short" is < 10 chars, should be skipped
        assert "Short" not in rules

    def test_bold_text_rules(self, importer):
        """Bold-wrapped text is extracted as rules."""
        content = "**Every response must end with a summary.**\n**Include key decisions and rationale.**\n**OK**\n"

        rules = importer._extract_rules(content)

        assert "Every response must end with a summary." in rules
        assert "Include key decisions and rationale." in rules
        # "OK" is < 10 chars, should be skipped
        assert "OK" not in rules


class TestAutoGeneratedSkipping:
    """Test skipping auto-generated sections."""

    def test_auto_generated_detected(self, importer):
        """Sections with AUTO-GENERATED markers are detected."""
        content = "<!-- AUTO-GENERATED -->\nThis is generated content.\n<!-- /AUTO-GENERATED -->"

        assert importer._is_auto_generated(content) is True

    def test_normal_content_not_detected(self, importer):
        """Normal content is not flagged as auto-generated."""
        content = "This is regular content with no markers."

        assert importer._is_auto_generated(content) is False


class TestMemoryCreation:
    """Test memory creation from CLAUDE.md parsing."""

    def test_context_type_directive(self, importer, tmp_path):
        """Imported memories have context_type set to 'directive'."""
        claude_md = tmp_path / "CLAUDE.md"
        claude_md.write_text("## Rules\n\n- Always write tests before implementation code\n")

        result = importer.import_source(claude_md)

        assert result.imported >= 1
        call_kwargs = importer._client.create.call_args
        assert call_kwargs.kwargs["context_type"] == "directive"

    def test_importance_set_to_085(self, importer, tmp_path):
        """Imported memories have importance set to 0.85."""
        claude_md = tmp_path / "CLAUDE.md"
        claude_md.write_text("## Rules\n\n- Always write tests before implementation code\n")

        result = importer.import_source(claude_md)

        call_kwargs = importer._client.create.call_args
        assert call_kwargs.kwargs["importance"] == 0.85

    def test_tags_include_source_and_heading(self, importer, tmp_path):
        """Tags include source:claude-md and heading-based tag."""
        claude_md = tmp_path / "CLAUDE.md"
        claude_md.write_text("## Testing rules\n\n- Write tests first using TDD methodology\n")

        result = importer.import_source(claude_md)

        call_kwargs = importer._client.create.call_args
        tags = call_kwargs.kwargs["tags"]
        assert "#source:claude-md" in tags
        assert any("testing-rules" in t for t in tags)

    def test_domain_from_heading(self, importer):
        """Domain is correctly mapped from heading text."""
        assert importer._domain_from_heading("Testing rules") == "testing"
        assert importer._domain_from_heading("Code quality") == "development"
        assert importer._domain_from_heading("Documentation") == "documentation"
        assert importer._domain_from_heading("Deployment pipeline") == "deployment"
        assert importer._domain_from_heading("Config setup") == "configuration"
        assert importer._domain_from_heading("Random stuff") == "workflow"


class TestEdgeCases:
    """Test edge cases in CLAUDE.md parsing."""

    def test_empty_sections_skipped(self, importer, tmp_path):
        """Sections with no extractable rules are skipped."""
        claude_md = tmp_path / "CLAUDE.md"
        claude_md.write_text("## Empty section\n\n\n\n## Another empty\n\n  \n")

        result = importer.import_source(claude_md)

        assert result.imported == 0

    def test_malformed_markdown_handled(self, importer, tmp_path):
        """Malformed markdown doesn't crash the importer."""
        claude_md = tmp_path / "CLAUDE.md"
        claude_md.write_text("###broken\n\n---\n\n```\nunclosed code\n\n## ##nested## headings##\n\n- Valid rule that should still be extracted from malformed markdown\n")

        result = importer.import_source(claude_md)

        # Should not raise, and may extract some rules
        assert isinstance(result, ImportResult)


class TestClaudeMdDryRun:
    """Test dry-run preview for CLAUDE.md."""

    def test_dry_run_preview(self, importer, tmp_path):
        """Dry run returns preview without writing memories."""
        claude_md = tmp_path / "CLAUDE.md"
        claude_md.write_text(SAMPLE_CLAUDE_MD)

        preview = importer.dry_run(claude_md)

        assert isinstance(preview, ImportPreview)
        assert preview.would_import > 0
        assert len(preview.sample_memories) <= 5
        # Dry run should NOT call create
        importer._client.create.assert_not_called()
